CREATE TABLE DEPT
(DEPTNO INT PRIMARY KEY,
 DNAME VARCHAR(18),
 HEAD CHAR(10)
);

CREATE TABLE STU
(STNO CHAR(10) PRIMARY KEY,
 NAME VARCHAR(20),
 AGE INT,
 MONIT CHAR(10),
 MACR INT,
 MICR INT,
 EDATE DATETIME,
 DEPTNO INT
 );

CREATE TABLE TEACHER
(TNO CHAR(10) PRIMARY KEY,
 NAME VARCHAR(20),
 AGE INT,
 WDATE DATETIME,
 DEPTNO INT
 );

CREATE INDEX IDEPTNO ON DEPT(DEPTNO);
CREATE INDEX ISTNO ON STU(STNO);
CREATE INDEX ITNO ON TEACHER(TNO);

