--1
SELECT *
FROM DEPT;

--2
SELECT NAME, AGE, MACR
FROM STU
ORDER BY MACR DESC;

--3
SELECT NAME
FROM STU
WHERE DEPTNO = 23;

--4
SELECT NAME
FROM STU
WHERE EDATE BETWEEN '01-01-2012' AND '01-01-2014';

--5
SELECT DEPTNO, COUNT(STNO) STUNUM, AVG(MACR) +AVG(ISNULL(MICR, 0)) AVGCR
FROM STU
GROUP BY DEPTNO;

--6
SELECT *
FROM STU
WHERE DEPTNO = 20 AND MACR > (SELECT AVG(MACR)
			  FROM STU
			  WHERE DEPTNO = 20);

--7
SELECT *
FROM STU
WHERE DEPTNO = 23 AND EDATE = (SELECT MIN(EDATE)
							   FROM STU);

--8
SELECT DEPT.DEPTNO, DNAME
FROM STU, DEPT
WHERE NAME = 'WANG DONG'
      AND STU.DEPTNO = DEPT.DEPTNO ;

--9
SELECT stu1.*
FROM STU stu1, STU stu2
WHERE stu1.MACR >= stu2.MACR AND stu1.MONIT = stu2.STNO AND stu1.STNO != stu2.STNO;

--10
SELECT STNO, NAME
FROM STU
WHERE DEPTNO = (SELECT DEPTNO
				FROM TEACHER
				WHERE TEACHER.NAME = 'ZHANG SAN');

--11
SELECT teacher1.NAME, DEPT.DNAME
FROM TEACHER teacher1, DEPT
WHERE DEPT.DEPTNO = teacher1.DEPTNO
	  AND teacher1.WDATE < (SELECT teacher2.WDATE
	  					   FROM TEACHER teacher2
	  					   WHERE DEPT.HEAD = teacher2.TNO);
